### ISSUE TITLE
机器人技术实验这50道题要全部背下来吗？

### ISSUE THREAD

**Issue by Mebius1916** [styitches/HFUT-CS#2]
老师说最后一次实验抽一个小时检查，每人抽一套题现场编写验收并且不能带任何资料，那这50道题是要背下来嘛？

**Comment by Mebius1916** [comment]
> 老师说最后一次实验抽一个小时检查，每人抽一套题现场编写验收并且不能带任何资料，那这50道题是要背下来嘛？

**Comment by hush-coder** [comment]
> 老师说最后一次实验抽一个小时检查，每人抽一套题现场编写验收并且不能带任何资料，那这50道题是要背下来嘛？

其实不用，挺水的其实，好记性不如烂笔头
